### ISSUE TITLE
[1.8] Missing SQLite library in ASP.NET Alpine Docker image

### ISSUE THREAD

**Issue by diogoan** [TheAxelander/OpenBudgeteer#233] opened 2024-04-02 02:06 UTC
**Describe the bug**
I've been trying to deploy the application by following the instructions on https://theaxelander.github.io/latest/quick-start/, but I had no success. I used both docker compose (by Portainer) and docker run methods, but I got the same error.

When I use the latest or pre-release image, I got the following error, and the container goes to Exited status:

> Error loading shared library libe_sqlite3: No such file or directory
>    at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
>    at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
>    at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
>    at SQLitePCL.Batteries_V2.Init()
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
>    at Microsoft.Data.Sqlite.SqliteConnection..cctor()
>    --- End of inner exception stack trace ---

(the entire log is here: [_openbudgeteer_logs.txt](https://github.com/TheAxelander/OpenBudgeteer/files/14830532/_openbudgeteer_logs.txt))

When I use the 1.7 image, I got no errors at all, but the web interface is not accessible either.

**To Reproduce**
1. Just follow the steps in https://theaxelander.github.io/latest/quick-start/, using SQLITE or TEMBDB.

**Expected behavior**
OpenBudgeteer is deployed successfully.

**Additional helpful details**
- OS: Ubuntu 22.04

**Comment by TheAxelander** [comment] 2024-04-02 13:46
Can confirm this. I need to check this the next days. 

In the meantime if you want to use `1.7` image or `1.7.1`, you need to change the port mapping to something like `8080:80` as this has been changed in the latest .NET version.

**Comment by TheAxelander** [comment] 2024-04-04 07:32
First root cause analysis: 

For some reason the Docker image doesn't has the required sqlite3 library. Non-Docker deployment works, so the issue should be somewhere in the new `aspnet:8.0-alpine` Docker image

**Comment by TheAxelander** [comment] 2024-04-04 08:09
Reverting back to `aspnet:8.0` default image seems to fix the issue. Docker image `axelander/openbudgeteer:dev` works again with SQLite

**Comment by TheAxelander** [comment] 2024-04-04 08:39
Should be fixed now with latest release

**Closed as completed by TheAxelander** 2024-04-04 08:39 UTC
Labels: bug, docker
