### ISSUE TITLE
When clicking on previous month, the month list shows Jan

### ISSUE THREAD

**Issue by charyouz** [TheAxelander/OpenBudgeteer#114] opened 2022-12-03 21:42 UTC
In transaction or bucket page, when clicking to show the previous month (the arrow to the left) it shows the correct month, but the dropdown menu shows "Jan" every other month. So for example now (December) clicking previous button would show "Jan" and clicking it again would show "Oct". Clicking a third time would again show "Jan" etc.
The data shown is correct though, it is only the dropdown menu bugging.

**Comment by TheAxelander** [comment] 2022-12-03 22:32
I already had the same issue on my side. I guess you are using Firefox, isn't it? This is the browser where it was only happening for me. For some reason this now popping up without any real change in the background. I didn't found the real root cause so far but as you said it's just showing the wrong value but in the backend the right month is selected.

**Comment by charyouz** [comment] 2022-12-03 22:35
Yes, using Firefox.
Haven't any others installed in my current PC so can't test with others.

**Comment by TheAxelander** [comment] 2022-12-03 22:46
No worries, I will have a look on this

**Comment by TheAxelander** [comment] 2022-12-06 08:38
Found [this](https://stackoverflow.com/questions/68134956/firefox-and-selected-selected) on the web and I could fix it on one location successfully. I now need to fix this on all Dropdowns and then I will release it in a bugfix update for version 1.6

**Comment by TheAxelander** [comment] 2022-12-12 11:21
Implemented fix on `pre-release`, I will keep this open for further testing until final release

**Comment by TheAxelander** [comment] 2023-01-01 09:18
Fixed with update `1.6.1`

**Closed as completed by TheAxelander** 2023-01-01 09:18 UTC
Labels: bug, blazor
